In [1]:
## Mount drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
## Set path
import os
os.chdir('/content/drive/MyDrive/ADM_HW5')

In [3]:
## Import Utils
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from datetime import datetime, date

In [4]:
## Load Data
with open('sx-stackoverflow-a2q.txt') as f:
    a2q = f.readlines()
    f.close()

In [5]:
## Load Data
with open('sx-stackoverflow-c2q.txt') as f:
    c2q = f.readlines()
    f.close()

In [6]:
## Load Data
with open('sx-stackoverflow-c2a.txt') as f:
    c2a = f.readlines()
    f.close()

In [7]:
## Init Graph
G = nx.DiGraph()

In [9]:
print(len(a2q), len(c2q), len(c2a))

17823525 20268151 25405374


In [8]:
## Merge Graph
t_start = datetime(2009, 10, 1)
t_end = datetime(2010, 10, 1)

for line in a2q:
    line = line.replace('\n', '')
    line = line.split(' ') 
    t = datetime.fromtimestamp(int(line[2]))
    t_truncated = date(t.year,t.month, t.day)
    if t_start <= t < t_end :
        if G.has_edge(line[0], line[1]) :
            G[line[0]][line[1]]['weight'] += 0.6
            G[line[0]][line[1]]['timestamp'].append(t_truncated)
        else :
            G.add_edge(line[0], line[1], weight=0.6)
            G[line[0]][line[1]]['timestamp']=[t_truncated]

for line in c2q:
    line = line.replace('\n', '')
    line = line.split(' ') 
    t = datetime.fromtimestamp(int(line[2]))
    t_truncated = date(t.year,t.month, t.day)
    if t_start <= t < t_end :
        if G.has_edge(line[0], line[1]) :
            G[line[0]][line[1]]['weight'] += 0.3
            G[line[0]][line[1]]['timestamp'].append(t_truncated)
        else :
            G.add_edge(line[0], line[1], weight=0.3)
            G[line[0]][line[1]]['timestamp']=[t_truncated]

for line in c2a:
    line = line.replace('\n', '')
    line = line.split(' ') 
    t = datetime.fromtimestamp(int(line[2]))
    t_truncated = date(t.year,t.month, t.day)
    if t_start <= t < t_end :
        if G.has_edge(line[0], line[1]) :
            G[line[0]][line[1]]['weight'] += 0.1
            G[line[0]][line[1]]['timestamp'].append(t_truncated)
        else :
            G.add_edge(line[0], line[1], weight=0.1)
            G[line[0]][line[1]]['timestamp']=[t_truncated]

### **Functionality 2**

In [9]:
time_start = date(2010, 1, 1)
time_end = date(2010, 3, 1)
subG = nx.DiGraph()
for edge in list(G.edges):
    if time_start <= G.edges[edge[0], edge[1]]['timestamp'][0] < time_end:
        subG.add_edge(edge[0], edge[1])
        subG[edge[0]][edge[1]]['weight'] = G.edges[edge[0], edge[1]]['weight']
        subG[edge[0]][edge[1]]['timestamp'] = G.edges[edge[0], edge[1]]['timestamp']

In [13]:
print(len(list(G.edges)), len(list(subG.edges)))

2288559 738715


In [14]:
subG.degree()

DiDegreeView({'13087': 148, '237462': 4, '242939': 10, '243160': 4, '135148': 65, '138578': 136, '185593': 444, '97855': 16, '74612': 181, '233087': 171, '49478': 389, '246407': 5, '71380': 36, '141172': 391, '20893': 37, '129032': 39, '101260': 17, '54193': 26, '250579': 17, '40655': 198, '20073': 20, '87698': 377, '259770': 4, '5618': 29, '155183': 17, '213469': 151, '173520': 217, '208670': 208, '244461': 24, '27946': 11, '233095': 37, '152598': 93, '151062': 58, '232687': 93, '15703': 32, '270307': 36, '85443': 16, '108493': 95, '232899': 215, '57007': 28, '248417': 58, '152365': 113, '195486': 116, '91769': 115, '23667': 72, '43818': 19, '182722': 2, '287862': 1, '202699': 53, '145143': 24, '224438': 11, '140403': 2, '296922': 3, '288280': 119, '81947': 92, '298187': 10, '221390': 29, '193670': 47, '311261': 8, '8411': 14, '243213': 256, '321022': 34, '150342': 33, '2017': 26, '201142': 208, '275807': 63, '317975': 86, '196319': 27, '209578': 45, '261708': 41, '10387': 70, '119549

In [19]:
len(subG.nodes)

89230

In [20]:
sub_edges = list(subG.edges)
count = 0
for edge in sub_edges:
    if edge[0] == '13087' or edge[1] == '13087':
        count += 1
    if edge[0] == edge[1] == '13087':
        count -= 1

degree_centrality = count / (len(subG) - 1)
print(degree_centrality)

0.0016586535767519528


In [23]:
nx.degree_centrality(subG)['13087']

0.0016586535767519528

In [1]:
nx.pagerank(subG, 0.25)['13087']

NameError: ignored

In [ ]:
score = alpha/len(subG) + (1-alpha)*sum(pi(j)/degree(j))

In [42]:
#list(subG.edges)
#print(subG.edges['141172','120329']['weight'], subG.edges['141172','120329']['timestamp'])
print(subG.edges['141172','120329']['weight'])
print(subG.edges['141172','120329']['timestamp'])

0.6
[datetime.date(2010, 4, 15), datetime.date(2010, 4, 16)]


In [ ]:
def funct_2(node, time_start, time_end, metric):
    '''
    Input:
        node <- a user/node
        time_start <- start of the interval of time
        time_end <- end of the interval of time
        metric <- one of the following metrics:
                    1. Betweenness
                    2. PageRank
                    3. Closeness Centrality
                    4. Degree Centrality
    '''
    subG = nx.DiGraph()
    edges = list(G.edges)
    for edge in edges:
        if time_start <= G.edges[edge[0], edge[1]]['timestamp'][0] < time_end:
            subG.add_edge(edge[0], edge[1])
            subG[edge[0]][edge[1]]['weight'] = G.edges[edge[0], edge[1]]['weight']
            subG[edge[0]][edge[1]]['timestamp'] = G.edges[edge[0], edge[1]]['timestamp']

    sub_edges = list(subG.edges)

    if metric == 1: # Betweenness centrality
    

    elif metric == 2: # PageRank

    elif metric == 3: # Closeness centrality

    elif metric == 4: # Degree centrality
        count = 0
        for edge in sub_edges:
            if edge[0] == str(node) or edge[1] == str(node):
                count += 1
            if edge[0] == edge[1] == str(node):
                count -= 1

        degree_centrality = count / (len(subG) - 1)
        print(f'Degree centrality of {node}:', degree_centrality)
    
    else:
        print('Insert a valid metric!')

In [47]:
print(nx.adjacency_matrix(subG).shape)

(89230, 89230)


In [ ]:
alpha = 0.25

P = (alpha/len(subG))*np.ones((len(subG), len(subG))) + (1-alpha)*(nx.adjaceny_matrix(subG))
print(P)

In [ ]:
def my_page_rank():
    my_weights = subG.edges['141172','120329']['weight']

In [41]:
### example
import numpy as np
import scipy as sc
import pandas as pd
from fractions import Fraction
def display_format(my_vector, my_decimal):
    return np.round((my_vector).astype(np.float), decimals=my_decimal)
my_dp = Fraction(1,3)
Mat = np.matrix([[0,0,1],
                [Fraction(1,2),0,0],
                [Fraction(1,2),1,0]])
Ex = np.zeros((3,3))
Ex[:] = my_dp
beta = 0.7
Al = beta * Mat + ((1-beta) * Ex)
r = np.matrix([my_dp, my_dp, my_dp])
r = np.transpose(r)
previous_r = r
for i in range(1,100):
    r = Al * r
    print (display_format(r,3))
    if (previous_r == r).all():
        break
    previous_r = r
print ("Final:\n", display_format(r,3))
print ("sum", np.sum(r))

[[0.333]
 [0.217]
 [0.45 ]]
[[0.415]
 [0.217]
 [0.368]]
[[0.358]
 [0.245]
 [0.397]]
[[0.378]
 [0.225]
 [0.397]]
[[0.378]
 [0.232]
 [0.39 ]]
[[0.373]
 [0.232]
 [0.395]]
[[0.376]
 [0.231]
 [0.393]]
[[0.375]
 [0.232]
 [0.393]]
[[0.375]
 [0.231]
 [0.394]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [0.393]]
[[0.375]
 [0.231]
 [

In [40]:
print(Ex[:])

[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
